export const ACTION_TYPES = {
    SET_INPUT_FIELD: 'SET_INPUT_FIELD',
    RESET_FORM: 'RESET_FORM',
    SET_ADD_APPLICATIONS: 'SET_ADD_APPLICATIONS',
    LOAD_APPLICATIONS: 'LOAD_APPLICATIONS',
    DELETE_APPLICATION: 'DELETE_APPLICATION',
    ARCHIVE_APPLICATION: 'ARCHIVE_APPLICATION',
    UNARCHIVE_APPLICATION: 'UNARCHIVE_APPLICATION',
    OPEN_DELETE_MODAL: 'OPEN_DELETE_MODAL',
    CLOSE_DELETE_MODAL: 'CLOSE_DELETE_MODAL',
}